version: '3.8'
services:
  diff-service:
    build: .
    ports:
      - "8000:8000"
    environment:
      - DEBUG=true
      - GITHUB_TOKEN=${GITHUB_TOKEN}
      - GITHUB_WEBHOOK_SECRET=${GITHUB_WEBHOOK_SECRET}
    volumes:
      - .:/app
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload